### ISSUE TITLE
Validate that $resource exists OnResourceBeforeSort

### ISSUE THREAD

**Issue by matdave** [Sterc/SEOTab#121]
Currently, the case OnResourceBeforeSort assumes that $resource exists and is found.  It creates a conflict with some plugins (e.g. SimpleCart) where the $resource variable may not exist. It should have an `if($resource)` before setting variables on the $resource.

**Comment by Mark-H** [comment]
Was just looking into this as well. While the event in SimpleCart and the one in the core are fired with the same parameters, the StercSEO plugin is looking at a $_POST variable that doesn't exist as it uses a different approach to the sort compared to the resource tree. 

Because of the $_POST not being there, and the lack of a sanity check in the plugin, it throws a fatal error `Uncaught Error: Call to a member function set() on null in /path/to/core/cache/includes/elements/modplugin/32.include.cache.php on line 277`

I could make SimpleCart stop firing the sort related events, but ideally, SEOTab would add in a quick conditional to make sure a resource was provided in the way it expects it. 

[modmore/SimpleCart#116]

**Comment by gpsietzema** [comment]
Good one Mat, we'll include it!

**Comment by sdrenth** [comment]
Since this check has been added, I will close this issue
