### ISSUE TITLE
Problems with updating FormIt after install SeoTab 

### ISSUE THREAD

**Issue by bYemma** [Sterc/SEOTab#123]
Hi, I installed SeoTab and then I wanted to update FormIt. But instead of updating FormIt SeoTab is installed again. Maybe something with cache goes wrong, both plugins use that modal with the newsletter form.
This happens me the second time, on two different sites on different servers.

**Comment by degoya** [comment]
i had the same problem. but also with other components. 
it allways reinstalled a previous installed component. 
after i reloaded the Package Manager page the installation worked well. 
But always the second installed packages tries to install the previous one until full page reload.
I had that problem with modmore and sterc Packages maybe it's caused by the setup of the packages. 

first i've been thinking it was a problem of my new server setup, but now after i read that someone else got the same problem i like to contribute my 50 cent.

**Comment by jonleverrier** [comment]
Not sure this problem is related to SeoTab. 

However, any plugin with a 2 step installation process will trigger this issue (modmore and sterc like to use these to capture peoples email addresses.

Doing a hard refresh on the installer page worked for me. You might have todo this each time for each plugin

**Comment by bYemma** [comment]
@jonleverrier You're right. I did recognize this, too.

So lets looking direct in the modx repo...
