### ISSUE TITLE
Sitemaps Missing Pages

### ISSUE THREAD

**Issue by alexcua** [Sterc/SEOTab#124]
My sitemaps in SEO Tab only has 48 pages from 202. Even pages that I've set to No in Findability are still in the sitemap.

**Comment by sdrenth** [comment]
@alexcua In order to exclude resources from the XML sitemap make sure the  option "Include this page in the Google Sitemap?" is set to No in the "Google Sitemap" tab. For resources that you are missing in the sitemap please check:

- If the "Include this page in the Google Sitemap?" option is set to Yes for those resources.
- The resource is published and of course not deleted.

**Comment by sdrenth** [comment]
@alexcua I will close this issue due to inactivity. If the issue remains please leave a comment and i will reopen this issue.
