### ISSUE TITLE
OnPageNotFound doesn't works correctly on site with many resources

### ISSUE THREAD

**Issue by degoya** [Sterc/SEOTab#61]
when i got a url i.E. 

mydomain.com/abc 

i get redirected to 

mydomain.com/projekte/packaging-design/medical/

instead of the 404 page. if i enter 

mydomain.com/ghi 

for example i get redirected to the 404 like i expect it.

After i disabled the plugin OnPageNotFound everything works like it should.
I think the LIKE request finds some kind of result and redirects it with 301 to a wrong resource instead of 404. 

The Site i got those problem has about 500+ Resources. Maybe thats the reason why the LIKE gets a hit. 

i've got the plugin on other sites without that effect.

**Comment by cristiantx** [comment]
I'm having the same issue as @degoya on my site. The site also have a lot of resources.

**Comment by joeke** [comment]
Hi,
Yes we've run into that issue ourselves as well. It's a tough one to fix actually because of the way the redirects are saved (in the properties json of the resource). 
We're actually working on a new version of Seotab, where the redirects are saved in a custom table, so that should solve this issue too. That version is almost ready, but ofcourse it's a major update so we've still got some testing to do with migrating currently saved redirects to the new format in the update script.
I'll keep you posted!

**Comment by gpsietzema** [comment]
SEO Tab 2.0 changes this. Still have to test a big site migration though.

**Comment by joeke** [comment]
@gpsietzema Have you tested this already?

**Comment by gpsietzema** [comment]
@joeke no, I would've closed it if I did ;)

**Comment by gpsietzema** [comment]
Fixed and tested in 2.0.0.
